version: "3.9"
services:
 db:
  image: postgres:16
  container_name: restaurante-db
  restart: always
  environment:
    POSTGRES_USER: admin
    POSTGRES_PASSWORD: admin
    POSTGRES_DB: restaurante
  ports:
   - "5433:5432"
  volumes:
    - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
